### ISSUE TITLE
There are same variables in other roles.

### ISSUE THREAD

**Issue by zakabluk** [lean-delivery/ansible-role-jboss#12]
SUMMARY
I am trying use  roles lean_delivery.jboss and lean_delivery.java in one my playbook . And have problems because both roles have same variables. 

ISSUE TYPE
Bug Report

Example:

ANSIBLE VERSION
2.5.5

STEPS TO REPRODUCE
I created playbook with variables:
```
  vars:
# lean_delivery.java
    java_path: /opt/java/
    download_path: /tmp/
    java_major_version: 7
    java_minor_version: 191
    java_arch: "x64"
    java_package: "jdk"
    transport: "web"
    transport_web: "https://s3.amazonaws.
# lean_delivery.jboss
    jboss_major_version: 6
    jboss_minor_version: 1
    jboss_patch_version: 0
    jboss_path: /app/jboss-eap-6.1/
    transport_web: https://s3.amazonaws.
    transport: "web"
```

> [WARNING]: While constructing a mapping from /app/clone_ansible/pex-devops/ansible/create_fe2/fe2_env.yml, line 24, column 5, found a duplicate dict key (transport_web). Using last defined value only.
> 
>  [WARNING]: While constructing a mapping from /app/clone_ansible/pex-devops/ansible/create_fe2/fe2_env.yml, line 24, column 5, found a duplicate dict key (transport). Using last defined value only.
>
