### ISSUE TITLE
prevent reinstall when a version already exists

### ISSUE THREAD

**Issue by jgainey** [lean-delivery/ansible-role-jboss#14]
##### SUMMARY

The current role does not allow to skip the unpacking/installation of the jboss packages.  This overwrites existing modified files such as standalone.xml

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

tasks/system/Linux.yml

##### ANSIBLE VERSION

```
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

EL 7/EL 8
##### STEPS TO REPRODUCE

```yaml
roles:
  jboss
    jboss_user: jboss
    jboss_group: jboss
    transport: web
    transport_web: "http://webserver/jboss/jboss-eap-7.4.0.zip"

```

##### EXPECTED RESULTS

Not overwrite customized configuration files

##### ACTUAL RESULTS

customized configuration files such as standalone.xml are overwritten 

```
N/A
```
